LOG_STDOUT = True
LOGGING_LEVEL = "DEBUG"
ENV = "development"

APP_VERSION = 1
IIIF_TARGET_VERSION = 2

SERVER = 'http://localhost:8181'
BASE_PATH = f'/api/v{APP_VERSION}/presentation/{IIIF_TARGET_VERSION}'
BASE_URL = f'{SERVER}{BASE_PATH}'

IMAGE_API_SERVER = 'http://localhost:8182'
IMAGE_API_BASE_PATH = '/iiif/2'
IMAGE_API_BASE_URL = f'{IMAGE_API_SERVER}{IMAGE_API_BASE_PATH}'

SQLALCHEMY_DATABASE_URI = 'sqlite:///db.sqlite3'
SQLALCHEMY_TRACK_MODIFICATIONS = False