""" Cascade all

Revision ID: a97fe6685bf6
Revises: 9a88382c235f
Create Date: 2022-09-01 16:20:06.288493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a97fe6685bf6'
down_revision = '9a88382c235f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('article_collection_id_fkey', 'article', type_='foreignkey')
    op.drop_constraint('page_collection_id_fkey', 'page', type_='foreignkey')
    op.drop_constraint('page2article_article_id_fkey', 'page2article', type_='foreignkey')
    op.drop_constraint('page2article_page_id_fkey', 'page2article', type_='foreignkey')
    op.create_foreign_key(None, 'page2article', 'article', ['article_id'], ['bibcode'], ondelete="CASCADE", onupdate="CASCADE")
    op.create_foreign_key(None, 'page2article', 'page', ['page_id'], ['id'], ondelete="CASCADE", onupdate="CASCADE")
    op.create_foreign_key(None, 'article', 'collection', ['collection_id'], ['id'], ondelete="CASCADE", onupdate="CASCADE")
    op.create_foreign_key(None, 'page', 'collection', ['collection_id'], ['id'], ondelete="CASCADE", onupdate="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('article_collection_id_fkey', 'article', type_='foreignkey')
    op.drop_constraint('page_collection_id_fkey', 'page', type_='foreignkey')
    op.drop_constraint('page2article_article_id_fkey', 'page2article', type_='foreignkey')
    op.drop_constraint('page2article_page_id_fkey', 'page2article', type_='foreignkey')
    op.create_foreign_key(None, 'article', 'collection', ['collection_id'], ['id'])
    op.create_foreign_key(None, 'page', 'collection', ['collection_id'], ['id'])
    op.create_foreign_key(None, 'page2article', 'article', ['article_id'], ['bibcode'])
    op.create_foreign_key(None, 'page2article', 'page', ['page_id'], ['id'])
    # ### end Alembic commands ###
