"""Changed foreign key on page2article

Revision ID: ee9fd2ef5b67
Revises: 5122837b57b7
Create Date: 2022-08-18 16:30:48.964626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee9fd2ef5b67'
down_revision = '5122837b57b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('page2article_article_id_fkey', 'page2article', type_='foreignkey')
    op.create_foreign_key(None, 'page2article', 'article', ['article_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('page2article_article_id_fkey', 'page2article', type_='foreignkey')
    op.create_foreign_key('page2article_article_id_fkey', 'page2article', 'article', ['article_id'], ['bibcode'])
    # ### end Alembic commands ###
