"""Inital alembic script

Revision ID: f47027cc246c
Revises: 
Create Date: 2022-06-14 15:24:49.965791

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'f47027cc246c'
down_revision = None
branch_labels = None
depends_on = None

pagecolor = sa.Enum('BW', 'Greyscale', 'Color', name='pagecolor')
pagetype = sa.Enum('Normal', 'FrontMatter', 'BackMatter', 'Insert', 'Plate', name='pagetype')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('journal', sa.String(), nullable=True),
    sa.Column('volume', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal', 'volume')
    )
    op.create_index('volume_index', 'collection', ['journal', 'volume'], unique=False)
    op.create_table('article',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('bibcode', sa.String(), nullable=True),
    sa.Column('collection_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('article_bibcode_index', 'article', ['bibcode'], unique=False)
    op.create_index('article_volume_index', 'article', ['collection_id'], unique=False)
    op.create_table('page',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('color_type', pagecolor, nullable=True),
    sa.Column('page_type', pagetype, nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('collection_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('volume_running_page_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'name'),
    sa.UniqueConstraint('collection_id', 'volume_running_page_num')
    )
    op.create_index('page_name_index', 'page', ['name'], unique=False)
    op.create_index('page_volume_index', 'page', ['collection_id'], unique=False)
    op.create_table('page2article',
    sa.Column('page_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('article_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.PrimaryKeyConstraint('page_id', 'article_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page2article')
    op.drop_index('page_volume_index', table_name='page')
    op.drop_index('page_name_index', table_name='page')
    op.drop_table('page')
    op.drop_index('article_volume_index', table_name='article')
    op.drop_index('article_bibcode_index', table_name='article')
    op.drop_table('article')
    op.drop_index('volume_index', table_name='collection')
    op.drop_table('collection')
    pagecolor.drop(op.get_bind(), checkfirst=False)
    pagetype.drop(op.get_bind(), checkfirst=False)

    # ### end Alembic commands ###
